steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/stunting-api', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/stunting-api']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args:
    - 'run'
    - 'deploy'
    - 'stunting-api'
    - '--image'
    - 'gcr.io/$PROJECT_ID/stunting-api'
    - '--platform'
    - 'managed'
    - '--region'
    - 'asia-southeast2'
    - '--allow-unauthenticated'

images:
- 'gcr.io/$PROJECT_ID/stunting-api'

options:
  logging: CLOUD_LOGGING_ONLY
